### PR TITLE
Fixes #92: Use su -c instead of the root shell

### LINKED ISSUE #92: `adb root` fails on vanilla Android with Magisk
On an Android 11 Google Pixel 3 `adb root` fails with `adbd cannot run as root in production builds`, though a current Magisk root is installed.

The workaround using `adb shell su` does work, however. We should implement that as well, if `adb root` throws.

### PR DESCRIPTION
**Pull request by zner0L**

### CODE REVIEW

File: src/android.ts [hunk 1]
```diff
@@ -672,38 +701,32 @@ export const androidApi = <RunTarget extends SupportedRunTarget<'android'>>(
...
+                "'com.wireguard.android/.model.TunnelManager\\$\\IntentReceiver'",
                 '-e',
                 'tunnel',
                 tunnelName,
             ]);
 
             const vpnIsStarted = await retryCondition(() => this._internal.isVpnEnabled());
             if (!vpnIsStarted) {
-                await deleteConfig();
+                // await deleteConfig();
```
Comment (baltpeter) [inline src/android.ts:729]: y?

File: src/android.ts [hunk 2]
```diff
@@ -608,25 +637,25 @@ export const androidApi = <RunTarget extends SupportedRunTarget<'android'>>(
...
         if (!(await this._internal.hasCertificateAuthority(certFilename))) return;
 
-        await this._internal.requireRoot('removeCertificateAuthority');
+        const { adbRootShell } = await this._internal.requireRoot('removeCertificateAuthority');
 
         await this._internal.overlayTmpfs('/system/etc/security/cacerts');
-        await adb(['shell', 'rm', `/system/etc/security/cacerts/${certFilename}`]);
+        await adbRootShell(['rm', `/system/etc/security/cacerts/${certFilename}`]);
     },
     async setProxy(_proxy) {
```
Comment (baltpeter) [inline src/android.ts:660]: Running the example script, the VPN never gets activated (I don't see the key icon in the top bar). But the check for the VPN doesn't fail, either.

Comment (baltpeter) [reply src/android.ts:660]: I don't see our config in the app.

File: src/android.ts [hunk 3]
```diff
@@ -2,12 +2,12 @@ import { decompress as decompressXz } from '@napi-rs/lzma/xz';
 import { runAndroidDevTool } from 'andromatic';
```
Comment (baltpeter) [inline src/android.ts:2]: In the example script, the app never gets started for me. Subsequently, `getPrefs()` fails:

```
file:///home/benni/coding/JS/tweasel/appstraction/node_modules/andromatic/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: /home/benni/.cache/andromatic/platform-tools/adb shell pidof -s de.hafas.android.db
    at makeError (file:///home/benni/coding/JS/tweasel/appstraction/node_modules/andromatic/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/benni/coding/JS/tweasel/appstraction/node_modules/andromatic/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.getPidForAppId (/home/benni/coding/JS/tweasel/appstraction/src/android.ts:604:28)
    at Object.getPrefs (/home/benni/coding/JS/tweasel/appstraction/src/android.ts:610:21)
    at <anonymous> (/home/benni/coding/JS/tweasel/appstraction/examples/android-device.ts:52:19) {
  shortMessage: 'Command failed with exit code 1: /home/benni/.cache/andromatic/platform-tools/adb shell pidof -s de.hafas.android.db',
  command: '/home/benni/.cache/andromatic/platform-tools/adb shell pidof -s de.hafas.android.db',
  escapedCommand: '"/home/benni/.cache/andromatic/platform-tools/adb" shell pidof -s de.hafas.android.db',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

File: src/android.ts (hunk 1 above)
Comment (zner0L) [reply src/android.ts:729]: oops, that was leftover form development.

File: src/android.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (zner0L) [reply src/android.ts:2]: I never see that error. What is the result of `frida-ps -Ua` on your device?

File: src/android.ts [hunk 4]
```diff
@@ -173,10 +173,42 @@ export const androidApi = <RunTarget extends SupportedRunTarget<'android'>>(
...
+                )
+            )
+                return {
+                    adbRootShell: (...args: ParametersExceptFirst<typeof runAndroidDevTool>) =>
+                        adb(['shell', 'su', '-c', ...(args[0] || [])], args[1]),
+                    adbRootPush: async (source: string, destination: string): Promise<void> => {
+                        const fileName = randomUUID();
+                        const tmpFolder = '/sdcard/appstraction-tmp';
+                        await adb(['shell', 'mkdir', '-p', tmpFolder]);
+                        await adb(['push', source, join(tmpFolder, fileName)]);
```
[the remark this answers is not in the document]
Comment (zner0L) [reply src/android.ts:188]: YOU said, it would be fine. But yes, you were wrong :D https://nodejs.org/api/path.html#pathjoinpaths

File: src/android.ts (hunk 3 above)
Comment (zner0L) [reply src/android.ts:2]: This does happen for me as well with the DB Navigator, but not with other apps. Did you test with the DB Navigator?

Comment (baltpeter) [reply src/android.ts:2]: I did use DBN, yes.

Comment (zner0L) [reply src/android.ts:2]: Actually, my problem was that my version of DB Navigator is a split APK, but the example only works for single APKs. Single APKs all work fine really.

**Comment by baltpeter** [comment]
Mea culpa. The problem was that I also had an iPhone connected (for charging). That's fine for adb but it confuses Frida. Without that, the example script runs fine (including DBN).

**Comment by baltpeter** [comment]
Might be a nice UX feature to fail in `ensureDevice()` if there is more than one device detected by adb and/or Frida.

File: README.md [hunk 5]
```diff
@@ -62,7 +62,7 @@ You can only run one device at a time with the current version.
 
 To use appstraction with a physical Android device, you need to enable USB debugging. You can do this by going to Settings -> System -> Developer options -> USB debugging.
 
-Some functions require the device to be rooted. The steps to do this vary depending on the device. We recommend using [Magisk](https://topjohnwu.github.io/Magisk/). After you have rooted the device, you need to enable rooted debugging via Settings -> System -> Developer options -> Rooted debugging.
+Most functions require the device to be rooted. The steps to do this vary depending on the device. We recommend using [Magisk](https://topjohnwu.github.io/Magisk/). After you have rooted the device, you need to allow `com.android.shell` to use super user privileges in Magisk. You can do this in the Magisk app and will be asked to do so the first time you run an analysis. Alternatively, you can also enable rooted debugging via Settings -> System -> Developer options -> Rooted debugging. However, this might not be available to you, depending on the distributuion of Android you run. Stock Android generally does not allow rooted debugging in production builds.
```
Comment (baltpeter) [inline README.md:65]: > You can do this in the Magisk app

Can you? I don't see an option to.

image

> Alternatively, you can also enable rooted debugging via Settings -> System -> Developer options -> Rooted debugging.

That isn't an alternative to the above. I don't see any reason to enable rd anymore. With the way the code is now, you still have to accept the Magisk prompt anyway.

File: src/android.ts [hunk 6]
```diff
@@ -672,30 +698,24 @@ export const androidApi = <RunTarget extends SupportedRunTarget<'android'>>(
...
-                appUser,
-                '/bin/sh',
-                '-c',
-                `"echo -n '${config}' > /data/data/com.wireguard.android/files/${tunnelName}.conf"`,
+            const { stdout: appUser } = await adbRootShell(['stat', '-c', '%U', '/data/data/com.wireguard.android']);
+            await adbRootShell([
+                `'su ${appUser} /bin/sh -c "echo -n '${Buffer.from(config, 'utf-8').toString(
+                    'base64'
+                )}' | base64 -d > /data/data/com.wireguard.android/files/${tunnelName}.conf"'`,
             ]);
```
Comment (baltpeter) [inline src/android.ts:706]: Running this in a fresh Android 13 emulator, I get:

```
file:///home/benni/coding/JS/tweasel/appstraction/node_modules/andromatic/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 127: /home/benni/.cache/andromatic/platform-tools/adb shell 'su u0_a159 /bin/sh -c "echo -n 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lHRHBxSmoxKzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3hFakFRQmdOVkJBTU0KQ1cxcGRHMXdjbTk0ZVRFU01CQUdBMVVFQ2d3SmJXbDBiWEJ5YjNoNU1CNFhEVEl3TVRFeE5qQTROVEkwTWxvWApEVEl6TVRFeE9EQTROVEkwTWxvd0tERVNNQkFHQTFVRUF3d0piV2wwYlhCeWIzaDVNUkl3RUFZRFZRUUtEQWx0CmFYUnRjSEp2ZUhrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkZUppNU5lZlYKZWJPNkE0UGczbVF2ak8vblpIZDJ3QnRybVp2cDFCYjVOUk5rZHh1VXdJOW5EMGZTMk5pZTZCMEs2WVJmb3dJbwoxVFQzSFZGZzNIeXNlaUxuOTN0WFg3ZUt4N3hidnY3NWphc0pYRjMwZW1mMFZaZEZBT3doby9vblF6TjJBWUJDCkxUOWlOMm0rbkxPSFU4RkgyWUg5UXR1em81ZUZCOHdFY3FpTFRjU2E2M3A1elVBZUJzWkx0OFYzanFPejhXemMKOXExd044U0hsalQvTzlpa0k0SDdncHFuMWZsSVVFeFZIckxrNm9KWTZpeXhSTjlyK055UnlVL3BhTnYxcUZOMApMSWdSc0hjR1pQa2ZrOSt6SjZuTWg1aFFLYkNWaTdMN1RuM3E1NWJrVW1TaE42Zk0yY0tRK2xaRGhpSGpOQXFsCkEwR04xZVpIcDVsakFnTUJBQUdqZ2RBd2djMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QVJCZ2xnaGtnQmh2aEMKQVFFRUJBTUNBZ1F3ZUFZRFZSMGxCSEV3YndZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApCQVlJS3dZQkJRVUhBd2dHQ2lzR0FRUUJnamNDQVJVR0Npc0dBUVFCZ2pjQ0FSWUdDaXNHQVFRQmdqY0tBd0VHCkNpc0dBUVFCZ2pjS0F3TUdDaXNHQVFRQmdqY0tBd1FHQ1dDR1NBR0crRUlFQVRBT0JnTlZIUThCQWY4RUJBTUMKQVFZd0hRWURWUjBPQkJZRUZLMDB4WkJwOTFWU0Q5aTRYeWo2SVVQdkJRa1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCWVFjcWdPcEVtSGtNQ2tIR0VUYVBKY2RiZzVtZmhCL2xiSG9OQkJ1Q3NhT1ZsbmZQam11elBxeVFJCmprTmhBaGx2WUFNZXFUM21QQlZzVGdHd3dmejducmRNSnlQa05IdC9wZ01OaVozR29iaXRmdlFDZTFJanVTemIKSGZodVJQeUhSZlFwTkJDQ2Jlc1RualZ4eXl1WndLMFk5OXdWV25KcUVvamFja2haQTZYUWxPbTAwQVMxb2lyeApDVFkrQ0F1RTRsS1U5RWxVRzhYRFQ3VWpjeDlvT1VPakQ2S3lPeklVd04rSkRMZ3lDVGEzYXA4NkZseVlMN0dhCkpBcUxWV2lpUWR5RkpzQmgrcTNXUzhxcng0OXBmZlZvYTB2ZHEvVG11S0g5YjN4dVdiLzdOYitLOHpUd1ZOZTcKSENJL3ZPUTNLUWlWMEtDODAvSVZDYzZlZ2YwVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf"'
/system/bin/sh: su u0_a159 /bin/sh -c "echo -n LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lHRHBxSmoxKzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3hFakFRQmdOVkJBTU0KQ1cxcGRHMXdjbTk0ZVRFU01CQUdBMVVFQ2d3SmJXbDBiWEJ5YjNoNU1CNFhEVEl3TVRFeE5qQTROVEkwTWxvWApEVEl6TVRFeE9EQTROVEkwTWxvd0tERVNNQkFHQTFVRUF3d0piV2wwYlhCeWIzaDVNUkl3RUFZRFZRUUtEQWx0CmFYUnRjSEp2ZUhrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkZUppNU5lZlYKZWJPNkE0UGczbVF2ak8vblpIZDJ3QnRybVp2cDFCYjVOUk5rZHh1VXdJOW5EMGZTMk5pZTZCMEs2WVJmb3dJbwoxVFQzSFZGZzNIeXNlaUxuOTN0WFg3ZUt4N3hidnY3NWphc0pYRjMwZW1mMFZaZEZBT3doby9vblF6TjJBWUJDCkxUOWlOMm0rbkxPSFU4RkgyWUg5UXR1em81ZUZCOHdFY3FpTFRjU2E2M3A1elVBZUJzWkx0OFYzanFPejhXemMKOXExd044U0hsalQvTzlpa0k0SDdncHFuMWZsSVVFeFZIckxrNm9KWTZpeXhSTjlyK055UnlVL3BhTnYxcUZOMApMSWdSc0hjR1pQa2ZrOSt6SjZuTWg1aFFLYkNWaTdMN1RuM3E1NWJrVW1TaE42Zk0yY0tRK2xaRGhpSGpOQXFsCkEwR04xZVpIcDVsakFnTUJBQUdqZ2RBd2djMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QVJCZ2xnaGtnQmh2aEMKQVFFRUJBTUNBZ1F3ZUFZRFZSMGxCSEV3YndZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApCQVlJS3dZQkJRVUhBd2dHQ2lzR0FRUUJnamNDQVJVR0Npc0dBUVFCZ2pjQ0FSWUdDaXNHQVFRQmdqY0tBd0VHCkNpc0dBUVFCZ2pjS0F3TUdDaXNHQVFRQmdqY0tBd1FHQ1dDR1NBR0crRUlFQVRBT0JnTlZIUThCQWY4RUJBTUMKQVFZd0hRWURWUjBPQkJZRUZLMDB4WkJwOTFWU0Q5aTRYeWo2SVVQdkJRa1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCWVFjcWdPcEVtSGtNQ2tIR0VUYVBKY2RiZzVtZmhCL2xiSG9OQkJ1Q3NhT1ZsbmZQam11elBxeVFJCmprTmhBaGx2WUFNZXFUM21QQlZzVGdHd3dmejducmRNSnlQa05IdC9wZ01OaVozR29iaXRmdlFDZTFJanVTemIKSGZodVJQeUhSZlFwTkJDQ2Jlc1RualZ4eXl1WndLMFk5OXdWV25KcUVvamFja2haQTZYUWxPbTAwQVMxb2lyeApDVFkrQ0F1RTRsS1U5RWxVRzhYRFQ3VWpjeDlvT1VPakQ2S3lPeklVd04rSkRMZ3lDVGEzYXA4NkZseVlMN0dhCkpBcUxWV2lpUWR5RkpzQmgrcTNXUzhxcng0OXBmZlZvYTB2ZHEvVG11S0g5YjN4dVdiLzdOYitLOHpUd1ZOZTcKSENJL3ZPUTNLUWlWMEtDODAvSVZDYzZlZ2YwVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf": inaccessible or not found
    at makeError (file:///home/benni/coding/JS/tweasel/appstraction/node_modules/andromatic/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/benni/coding/JS/tweasel/appstraction/node_modules/andromatic/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.setProxy (/home/benni/coding/JS/tweasel/appstraction/src/android.ts:703:13)
    at <anonymous> (/home/benni/coding/JS/tweasel/appstraction/examples/android-emulator.ts:31:30) {
  shortMessage: `Command failed with exit code 127: /home/benni/.cache/andromatic/platform-tools/adb shell 'su u0_a159 /bin/sh -c "echo -n 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lHRHBxSmoxKzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3hFakFRQmdOVkJBTU0KQ1cxcGRHMXdjbTk0ZVRFU01CQUdBMVVFQ2d3SmJXbDBiWEJ5YjNoNU1CNFhEVEl3TVRFeE5qQTROVEkwTWxvWApEVEl6TVRFeE9EQTROVEkwTWxvd0tERVNNQkFHQTFVRUF3d0piV2wwYlhCeWIzaDVNUkl3RUFZRFZRUUtEQWx0CmFYUnRjSEp2ZUhrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkZUppNU5lZlYKZWJPNkE0UGczbVF2ak8vblpIZDJ3QnRybVp2cDFCYjVOUk5rZHh1VXdJOW5EMGZTMk5pZTZCMEs2WVJmb3dJbwoxVFQzSFZGZzNIeXNlaUxuOTN0WFg3ZUt4N3hidnY3NWphc0pYRjMwZW1mMFZaZEZBT3doby9vblF6TjJBWUJDCkxUOWlOMm0rbkxPSFU4RkgyWUg5UXR1em81ZUZCOHdFY3FpTFRjU2E2M3A1elVBZUJzWkx0OFYzanFPejhXemMKOXExd044U0hsalQvTzlpa0k0SDdncHFuMWZsSVVFeFZIckxrNm9KWTZpeXhSTjlyK055UnlVL3BhTnYxcUZOMApMSWdSc0hjR1pQa2ZrOSt6SjZuTWg1aFFLYkNWaTdMN1RuM3E1NWJrVW1TaE42Zk0yY0tRK2xaRGhpSGpOQXFsCkEwR04xZVpIcDVsakFnTUJBQUdqZ2RBd2djMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QVJCZ2xnaGtnQmh2aEMKQVFFRUJBTUNBZ1F3ZUFZRFZSMGxCSEV3YndZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApCQVlJS3dZQkJRVUhBd2dHQ2lzR0FRUUJnamNDQVJVR0Npc0dBUVFCZ2pjQ0FSWUdDaXNHQVFRQmdqY0tBd0VHCkNpc0dBUVFCZ2pjS0F3TUdDaXNHQVFRQmdqY0tBd1FHQ1dDR1NBR0crRUlFQVRBT0JnTlZIUThCQWY4RUJBTUMKQVFZd0hRWURWUjBPQkJZRUZLMDB4WkJwOTFWU0Q5aTRYeWo2SVVQdkJRa1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCWVFjcWdPcEVtSGtNQ2tIR0VUYVBKY2RiZzVtZmhCL2xiSG9OQkJ1Q3NhT1ZsbmZQam11elBxeVFJCmprTmhBaGx2WUFNZXFUM21QQlZzVGdHd3dmejducmRNSnlQa05IdC9wZ01OaVozR29iaXRmdlFDZTFJanVTemIKSGZodVJQeUhSZlFwTkJDQ2Jlc1RualZ4eXl1WndLMFk5OXdWV25KcUVvamFja2haQTZYUWxPbTAwQVMxb2lyeApDVFkrQ0F1RTRsS1U5RWxVRzhYRFQ3VWpjeDlvT1VPakQ2S3lPeklVd04rSkRMZ3lDVGEzYXA4NkZseVlMN0dhCkpBcUxWV2lpUWR5RkpzQmgrcTNXUzhxcng0OXBmZlZvYTB2ZHEvVG11S0g5YjN4dVdiLzdOYitLOHpUd1ZOZTcKSENJL3ZPUTNLUWlWMEtDODAvSVZDYzZlZ2YwVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf"'`,
  command: `/home/benni/.cache/andromatic/platform-tools/adb shell 'su u0_a159 /bin/sh -c "echo -n 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lHRHBxSmoxKzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3hFakFRQmdOVkJBTU0KQ1cxcGRHMXdjbTk0ZVRFU01CQUdBMVVFQ2d3SmJXbDBiWEJ5YjNoNU1CNFhEVEl3TVRFeE5qQTROVEkwTWxvWApEVEl6TVRFeE9EQTROVEkwTWxvd0tERVNNQkFHQTFVRUF3d0piV2wwYlhCeWIzaDVNUkl3RUFZRFZRUUtEQWx0CmFYUnRjSEp2ZUhrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkZUppNU5lZlYKZWJPNkE0UGczbVF2ak8vblpIZDJ3QnRybVp2cDFCYjVOUk5rZHh1VXdJOW5EMGZTMk5pZTZCMEs2WVJmb3dJbwoxVFQzSFZGZzNIeXNlaUxuOTN0WFg3ZUt4N3hidnY3NWphc0pYRjMwZW1mMFZaZEZBT3doby9vblF6TjJBWUJDCkxUOWlOMm0rbkxPSFU4RkgyWUg5UXR1em81ZUZCOHdFY3FpTFRjU2E2M3A1elVBZUJzWkx0OFYzanFPejhXemMKOXExd044U0hsalQvTzlpa0k0SDdncHFuMWZsSVVFeFZIckxrNm9KWTZpeXhSTjlyK055UnlVL3BhTnYxcUZOMApMSWdSc0hjR1pQa2ZrOSt6SjZuTWg1aFFLYkNWaTdMN1RuM3E1NWJrVW1TaE42Zk0yY0tRK2xaRGhpSGpOQXFsCkEwR04xZVpIcDVsakFnTUJBQUdqZ2RBd2djMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QVJCZ2xnaGtnQmh2aEMKQVFFRUJBTUNBZ1F3ZUFZRFZSMGxCSEV3YndZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApCQVlJS3dZQkJRVUhBd2dHQ2lzR0FRUUJnamNDQVJVR0Npc0dBUVFCZ2pjQ0FSWUdDaXNHQVFRQmdqY0tBd0VHCkNpc0dBUVFCZ2pjS0F3TUdDaXNHQVFRQmdqY0tBd1FHQ1dDR1NBR0crRUlFQVRBT0JnTlZIUThCQWY4RUJBTUMKQVFZd0hRWURWUjBPQkJZRUZLMDB4WkJwOTFWU0Q5aTRYeWo2SVVQdkJRa1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCWVFjcWdPcEVtSGtNQ2tIR0VUYVBKY2RiZzVtZmhCL2xiSG9OQkJ1Q3NhT1ZsbmZQam11elBxeVFJCmprTmhBaGx2WUFNZXFUM21QQlZzVGdHd3dmejducmRNSnlQa05IdC9wZ01OaVozR29iaXRmdlFDZTFJanVTemIKSGZodVJQeUhSZlFwTkJDQ2Jlc1RualZ4eXl1WndLMFk5OXdWV25KcUVvamFja2haQTZYUWxPbTAwQVMxb2lyeApDVFkrQ0F1RTRsS1U5RWxVRzhYRFQ3VWpjeDlvT1VPakQ2S3lPeklVd04rSkRMZ3lDVGEzYXA4NkZseVlMN0dhCkpBcUxWV2lpUWR5RkpzQmgrcTNXUzhxcng0OXBmZlZvYTB2ZHEvVG11S0g5YjN4dVdiLzdOYitLOHpUd1ZOZTcKSENJL3ZPUTNLUWlWMEtDODAvSVZDYzZlZ2YwVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf"'`,
  escapedCommand: `"/home/benni/.cache/andromatic/platform-tools/adb" shell "'su u0_a159 /bin/sh -c \\"echo -n 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lHRHBxSmoxKzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3hFakFRQmdOVkJBTU0KQ1cxcGRHMXdjbTk0ZVRFU01CQUdBMVVFQ2d3SmJXbDBiWEJ5YjNoNU1CNFhEVEl3TVRFeE5qQTROVEkwTWxvWApEVEl6TVRFeE9EQTROVEkwTWxvd0tERVNNQkFHQTFVRUF3d0piV2wwYlhCeWIzaDVNUkl3RUFZRFZRUUtEQWx0CmFYUnRjSEp2ZUhrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkZUppNU5lZlYKZWJPNkE0UGczbVF2ak8vblpIZDJ3QnRybVp2cDFCYjVOUk5rZHh1VXdJOW5EMGZTMk5pZTZCMEs2WVJmb3dJbwoxVFQzSFZGZzNIeXNlaUxuOTN0WFg3ZUt4N3hidnY3NWphc0pYRjMwZW1mMFZaZEZBT3doby9vblF6TjJBWUJDCkxUOWlOMm0rbkxPSFU4RkgyWUg5UXR1em81ZUZCOHdFY3FpTFRjU2E2M3A1elVBZUJzWkx0OFYzanFPejhXemMKOXExd044U0hsalQvTzlpa0k0SDdncHFuMWZsSVVFeFZIckxrNm9KWTZpeXhSTjlyK055UnlVL3BhTnYxcUZOMApMSWdSc0hjR1pQa2ZrOSt6SjZuTWg1aFFLYkNWaTdMN1RuM3E1NWJrVW1TaE42Zk0yY0tRK2xaRGhpSGpOQXFsCkEwR04xZVpIcDVsakFnTUJBQUdqZ2RBd2djMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QVJCZ2xnaGtnQmh2aEMKQVFFRUJBTUNBZ1F3ZUFZRFZSMGxCSEV3YndZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApCQVlJS3dZQkJRVUhBd2dHQ2lzR0FRUUJnamNDQVJVR0Npc0dBUVFCZ2pjQ0FSWUdDaXNHQVFRQmdqY0tBd0VHCkNpc0dBUVFCZ2pjS0F3TUdDaXNHQVFRQmdqY0tBd1FHQ1dDR1NBR0crRUlFQVRBT0JnTlZIUThCQWY4RUJBTUMKQVFZd0hRWURWUjBPQkJZRUZLMDB4WkJwOTFWU0Q5aTRYeWo2SVVQdkJRa1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCWVFjcWdPcEVtSGtNQ2tIR0VUYVBKY2RiZzVtZmhCL2xiSG9OQkJ1Q3NhT1ZsbmZQam11elBxeVFJCmprTmhBaGx2WUFNZXFUM21QQlZzVGdHd3dmejducmRNSnlQa05IdC9wZ01OaVozR29iaXRmdlFDZTFJanVTemIKSGZodVJQeUhSZlFwTkJDQ2Jlc1RualZ4eXl1WndLMFk5OXdWV25KcUVvamFja2haQTZYUWxPbTAwQVMxb2lyeApDVFkrQ0F1RTRsS1U5RWxVRzhYRFQ3VWpjeDlvT1VPakQ2S3lPeklVd04rSkRMZ3lDVGEzYXA4NkZseVlMN0dhCkpBcUxWV2lpUWR5RkpzQmgrcTNXUzhxcng0OXBmZlZvYTB2ZHEvVG11S0g5YjN4dVdiLzdOYitLOHpUd1ZOZTcKSENJL3ZPUTNLUWlWMEtDODAvSVZDYzZlZ2YwVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf\\"'"`,
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/system/bin/sh: su u0_a159 /bin/sh -c "echo -n LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lHRHBxSmoxKzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3hFakFRQmdOVkJBTU0KQ1cxcGRHMXdjbTk0ZVRFU01CQUdBMVVFQ2d3SmJXbDBiWEJ5YjNoNU1CNFhEVEl3TVRFeE5qQTROVEkwTWxvWApEVEl6TVRFeE9EQTROVEkwTWxvd0tERVNNQkFHQTFVRUF3d0piV2wwYlhCeWIzaDVNUkl3RUFZRFZRUUtEQWx0CmFYUnRjSEp2ZUhrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkZUppNU5lZlYKZWJPNkE0UGczbVF2ak8vblpIZDJ3QnRybVp2cDFCYjVOUk5rZHh1VXdJOW5EMGZTMk5pZTZCMEs2WVJmb3dJbwoxVFQzSFZGZzNIeXNlaUxuOTN0WFg3ZUt4N3hidnY3NWphc0pYRjMwZW1mMFZaZEZBT3doby9vblF6TjJBWUJDCkxUOWlOMm0rbkxPSFU4RkgyWUg5UXR1em81ZUZCOHdFY3FpTFRjU2E2M3A1elVBZUJzWkx0OFYzanFPejhXemMKOXExd044U0hsalQvTzlpa0k0SDdncHFuMWZsSVVFeFZIckxrNm9KWTZpeXhSTjlyK055UnlVL3BhTnYxcUZOMApMSWdSc0hjR1pQa2ZrOSt6SjZuTWg1aFFLYkNWaTdMN1RuM3E1NWJrVW1TaE42Zk0yY0tRK2xaRGhpSGpOQXFsCkEwR04xZVpIcDVsakFnTUJBQUdqZ2RBd2djMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QVJCZ2xnaGtnQmh2aEMKQVFFRUJBTUNBZ1F3ZUFZRFZSMGxCSEV3YndZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApCQVlJS3dZQkJRVUhBd2dHQ2lzR0FRUUJnamNDQVJVR0Npc0dBUVFCZ2pjQ0FSWUdDaXNHQVFRQmdqY0tBd0VHCkNpc0dBUVFCZ2pjS0F3TUdDaXNHQVFRQmdqY0tBd1FHQ1dDR1NBR0crRUlFQVRBT0JnTlZIUThCQWY4RUJBTUMKQVFZd0hRWURWUjBPQkJZRUZLMDB4WkJwOTFWU0Q5aTRYeWo2SVVQdkJRa1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCWVFjcWdPcEVtSGtNQ2tIR0VUYVBKY2RiZzVtZmhCL2xiSG9OQkJ1Q3NhT1ZsbmZQam11elBxeVFJCmprTmhBaGx2WUFNZXFUM21QQlZzVGdHd3dmejducmRNSnlQa05IdC9wZ01OaVozR29iaXRmdlFDZTFJanVTemIKSGZodVJQeUhSZlFwTkJDQ2Jlc1RualZ4eXl1WndLMFk5OXdWV25KcUVvamFja2haQTZYUWxPbTAwQVMxb2lyeApDVFkrQ0F1RTRsS1U5RWxVRzhYRFQ3VWpjeDlvT1VPakQ2S3lPeklVd04rSkRMZ3lDVGEzYXA4NkZseVlMN0dhCkpBcUxWV2lpUWR5RkpzQmgrcTNXUzhxcng0OXBmZlZvYTB2ZHEvVG11S0g5YjN4dVdiLzdOYitLOHpUd1ZOZTcKSENJL3ZPUTNLUWlWMEtDODAvSVZDYzZlZ2YwVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf": inaccessible or not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Comment (baltpeter) [reply src/android.ts:706]: Curiously, if I run the command[^1] manually in a terminal, it does work.

[^1]: `/home/benni/.cache/andromatic/platform-tools/adb shell 'su u0_a159 /bin/sh -c "echo -n 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lHRHBxSmoxKzVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DZ3hFakFRQmdOVkJBTU0KQ1cxcGRHMXdjbTk0ZVRFU01CQUdBMVVFQ2d3SmJXbDBiWEJ5YjNoNU1CNFhEVEl3TVRFeE5qQTROVEkwTWxvWApEVEl6TVRFeE9EQTROVEkwTWxvd0tERVNNQkFHQTFVRUF3d0piV2wwYlhCeWIzaDVNUkl3RUFZRFZRUUtEQWx0CmFYUnRjSEp2ZUhrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNkZUppNU5lZlYKZWJPNkE0UGczbVF2ak8vblpIZDJ3QnRybVp2cDFCYjVOUk5rZHh1VXdJOW5EMGZTMk5pZTZCMEs2WVJmb3dJbwoxVFQzSFZGZzNIeXNlaUxuOTN0WFg3ZUt4N3hidnY3NWphc0pYRjMwZW1mMFZaZEZBT3doby9vblF6TjJBWUJDCkxUOWlOMm0rbkxPSFU4RkgyWUg5UXR1em81ZUZCOHdFY3FpTFRjU2E2M3A1elVBZUJzWkx0OFYzanFPejhXemMKOXExd044U0hsalQvTzlpa0k0SDdncHFuMWZsSVVFeFZIckxrNm9KWTZpeXhSTjlyK055UnlVL3BhTnYxcUZOMApMSWdSc0hjR1pQa2ZrOSt6SjZuTWg1aFFLYkNWaTdMN1RuM3E1NWJrVW1TaE42Zk0yY0tRK2xaRGhpSGpOQXFsCkEwR04xZVpIcDVsakFnTUJBQUdqZ2RBd2djMHdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QVJCZ2xnaGtnQmh2aEMKQVFFRUJBTUNBZ1F3ZUFZRFZSMGxCSEV3YndZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApCQVlJS3dZQkJRVUhBd2dHQ2lzR0FRUUJnamNDQVJVR0Npc0dBUVFCZ2pjQ0FSWUdDaXNHQVFRQmdqY0tBd0VHCkNpc0dBUVFCZ2pjS0F3TUdDaXNHQVFRQmdqY0tBd1FHQ1dDR1NBR0crRUlFQVRBT0JnTlZIUThCQWY4RUJBTUMKQVFZd0hRWURWUjBPQkJZRUZLMDB4WkJwOTFWU0Q5aTRYeWo2SVVQdkJRa1BNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCWVFjcWdPcEVtSGtNQ2tIR0VUYVBKY2RiZzVtZmhCL2xiSG9OQkJ1Q3NhT1ZsbmZQam11elBxeVFJCmprTmhBaGx2WUFNZXFUM21QQlZzVGdHd3dmejducmRNSnlQa05IdC9wZ01OaVozR29iaXRmdlFDZTFJanVTemIKSGZodVJQeUhSZlFwTkJDQ2Jlc1RualZ4eXl1WndLMFk5OXdWV25KcUVvamFja2haQTZYUWxPbTAwQVMxb2lyeApDVFkrQ0F1RTRsS1U5RWxVRzhYRFQ3VWpjeDlvT1VPakQ2S3lPeklVd04rSkRMZ3lDVGEzYXA4NkZseVlMN0dhCkpBcUxWV2lpUWR5RkpzQmgrcTNXUzhxcng0OXBmZlZvYTB2ZHEvVG11S0g5YjN4dVdiLzdOYitLOHpUd1ZOZTcKSENJL3ZPUTNLUWlWMEtDODAvSVZDYzZlZ2YwVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf"'`

Comment (baltpeter) [reply src/android.ts:706]: There's also a bug in the emulator example script (introduced by me): The WireGuard config is in `process.argv[6]`.

I was a bit surprised at how long the WireGuard config was supposedly. Correct command (but still failing):

```sh
/home/benni/.cache/andromatic/platform-tools/adb shell 'su u0_a159 /bin/sh -c "echo -n 'W0ludGVyZmFjZV0KUHJpdmF0ZUtleSA9IEVGUlRMSGxhRmZFOWRYbnU0VHJkRTFvc2JUa0ZFMFMxMTA5Z2FMaUd2MXM9CkFkZHJlc3MgPSAxMC4wLjAuMS8zMgpETlMgPSAxMC4wLjAuNTMKCltQZWVyXQpQdWJsaWNLZXkgPSBHYmd4b3o4YiswOEJneFlBdmhlTTZPbUZUMDlhYVNReHRVUldZU2htOWkwPQpBbGxvd2VkSVBzID0gMC4wLjAuMC8wCkVuZHBvaW50ID0gMTAuMC4wLjY4OjUxODIwCg==' | base64 -d > /data/data/com.wireguard.android/files/appstraction.conf"'
```

Comment (baltpeter) [reply src/android.ts:706]: Other than this, it does also work in an emulator.

**Review by baltpeter — CHANGES_REQUESTED** [review]

File: README.md (hunk 5 above)
Comment (zner0L) [reply README.md:65]: > Can you? I don't see an option to.
Only after the shell first requested it.
> I don't see any reason to enable rd anymore. With the way the code is now, you still have to accept the Magisk prompt anyway.
Yes and no. If you enable rooted debugging, you do not need to interact with the phone at all, because you can still acquire root rights without accepting the prompt.

File: src/android.ts (hunk 6 above)
Comment (zner0L) [reply src/android.ts:706]: Oh, this is annoying: Android uses a non-POSIX `su` (https://stackoverflow.com/questions/55506205/android-shell-su-doesnt-have-option-c)

Comment (zner0L) [reply src/android.ts]: Wow. This took forever to fix. Why does Android not respect POSIX :(((

**Review by baltpeter — CHANGES_REQUESTED** [review]
Ugh, that looks painful. :/ One more problem, I'm afraid but the escaping workaround does work from my testing.

File: src/android.ts [hunk 7]
```diff
@@ -138,10 +142,8 @@ export const androidApi = <RunTarget extends SupportedRunTarget<'android'>>(
             const { stdout: fridaCheck } = await python('frida-ps', ['-U'], { reject: false });
             if (fridaCheck.includes('frida-server')) return;
 
-            await this.requireRoot('Frida');
-
-            await adb(['shell', 'chmod', '755', '/data/local/tmp/frida-server']);
-            await adb(['shell', '-x', '/data/local/tmp/frida-server', '--daemonize']);
+            await adbRootShell(['chmod', '755', '/data/local/tmp/frida-server']);
+            adbRootShell(['/data/local/tmp/frida-server', '--daemonize']);
```
[the remark this answers is not in the document]
Comment (zner0L) [reply src/android.ts]: Probably because frida is already running on your device.

**Review by baltpeter — APPROVED** [review]
Thank you!

**Review by MSALARy688889u — COMMENTED** [review]
Deleted magisk call
