### PR TITLE
iOS: Support for managing proxies and certificate authorities

### LINKED ISSUE #32: Starting frida might fail after device reset
In the emulator example, the device is first ensured and then reset to a snapshot. After the reset, sometimes the frida server can not be started again in `ensureFrida`. On my linux machine, this sometimes fails with `device offline` (see detailed error message below), but it also works most of the time.

```
(node:20114) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: adb shell "nohup /data/local/tmp/frida-server >/dev/null 2>&1 &"
adb: device offline
    at makeError (file:///home/zner0L/Programming/Activism/TrackingWeasel/appstraction/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/zner0L/Programming/Activism/TrackingWeasel/appstraction/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.ensureFrida (/home/zner0L/Programming/Activism/TrackingWeasel/appstraction/src/android.ts:54:13)
    at Object.ensureDevice (/home/zner0L/Programming/Activism/TrackingWeasel/appstraction/src/android.ts:89:9)
    at null.<anonymous> (/home/zner0L/Programming/Activism/TrackingWeasel/appstraction/examples/android-emulator.ts:17:5)
```

Funnily enough, now I cannot reproduce this anymore.

### PR DESCRIPTION
**Pull request by baltpeter**
With this PR, I'm catching iOS up with the new features added for Android in #27.

**This is based on #27, which needs to be merged first.**

Functions implemented so far:

* `installCertificateAuthority()` and `removeCertificateAuthority()` to install or remove a certificate authority as a trusted root CA on the device. Caveat: For the CA to be trusted automatically, the user needs to perform a one-time setup step. (#44)
* `setProxy()` to either set or disable the global proxy settings. (#25)

Additionally implemented:

* `stopApp()` to force-stop an app. (#37)
* `isAppInstalled()` to check whether an app is already installed on the device. (#41)

Unrelated to the rest of the PR but also added here (since I didn't want to stack yet another PR):

* Retry starting Frida on Android if that fails to hopefully fix #32.
* Automatically install Frida in `ensureDevice()` on Android. The device preparation instructions on Android are now delightfully short. \o/ (#39)

### CODE REVIEW

File: examples/ios-device.ts [hunk 1]
```diff
@@ -15,11 +15,16 @@ import { parseAppMeta, pause, platformApi } from '../src/index';
...
-    const proxyPort = process.argv[5];
+    const caCertPath = process.argv[4];
+    const proxyHost = process.argv[5];
+    const proxyPort = process.argv[6];
 
     await ios.ensureDevice();
 
+    if (caCertPath) {
+        await ios.removeCertificateAuthority(caCertPath);
+        await ios.installCertificateAuthority(caCertPath);
```
Comment (zner0L) [inline examples/ios-device.ts:26]: I think we should maybe include a prompt or something waiting for you to manually accept the cert once to emphasize in the example that this is a manual task currently.

File: src/ios.ts [hunk 2]
```diff
@@ -119,7 +119,16 @@ export const iosApi = <RunTarget extends SupportedRunTarget<'ios'>>(
...
 
-    isAppInstalled: asyncUnimplemented('isAppInstalled') as never,
+    isAppInstalled: async (appId) => {
+        const { stdout } = await execa('ideviceinstaller', ['-l', '-o', 'list_all']);
+        return (
+            stdout
+                .split('\n')
+                // The first line is the header.
+                .slice(1)
+                .some((l) => l.startsWith(`${appId},`))
```
Comment (zner0L) [inline src/ios.ts:129]: Why don’t you just `grep`?

**Review by zner0L — CHANGES_REQUESTED** [review]

**Comment by zner0L** [comment]
I haven’t tested it on the device, yet, but this is what I found reading through the code.

File: src/index.ts [hunk 3]
```diff
@@ -147,11 +187,70 @@ export type PlatformApi<Platform extends SupportedPlatform, RunTarget extends Su
...
+     * WireGuard tunnel. Otherwise, it will set the global proxy on the device.
+     *
+     * WireGuard is currently only supported on Android. Enabling a WireGuard tunnel requires the `root` capability.
+     *
+     * @remarks
+     * The WireGuard integration will create a new tunnel in the app called `appstraction` and delete it when the proxy
+     * is stopped. If you have an existing tunnel with the same name, it will be overridden.
+     * @param proxy The proxy to set, or `null` to disable the proxy. If you have enabled the `wireguard` capability,
+     *   this is a string of the full WireGuard configuration to use.
+     */
```
Comment (zner0L) [inline src/index.ts:235]: I was just think as well, that we should mention that we set the proxy in iOS only for a WiFi connection and not cellular data. I know it is kinda ridiculous, because the method requires the `ssh` capability and it is unlikely this works over cellular, but I think this should still be mentioned, because we don't know the purposes someone might want to use this for. 

Also, I looked into WireGuard on iOS for a moment and they seem to support VPNs on cellular as well, so if we want to enable WireGuard on iOS we could support cellular, too.

File: examples/ios-device.ts (hunk 1 above)
Comment (baltpeter) [reply examples/ios-device.ts:26]: I like the idea but it would be annoying to always have to confirm that prompt in the example (especially for us, I use those for testing). I would much rather invest the time needed to do this properly into actually fixing the problem or at least being able to check whether the user has done that once.

As a compromise, I'll add a `console.log()`.

File: src/ios.ts (hunk 2 above)
Comment (baltpeter) [reply src/ios.ts:129]: I prefer not to rely on shell stuff and would rather do things in JS.

**Comment by baltpeter** [comment]
This should probably be rebased on `main` after #27 is merged but before this is merged.

File: src/ios.ts (hunk 2 above)
Comment (zner0L) [reply src/ios.ts:164]: But `grep` is part of POSIX?

File: src/ios.ts [hunk 4]
```diff
@@ -198,7 +249,14 @@ export const iosApi = <RunTarget extends SupportedRunTarget<'ios'>>(
...
     installCertificateAuthority: asyncUnimplemented('installCertificateAuthority') as never,
     removeCertificateAuthority: asyncUnimplemented('removeCertificateAuthority') as never,
-    setProxy: asyncUnimplemented('setProxy') as never,
+    setProxy: async (proxy) => {
+        if (!options.capabilities.includes('frida')) throw new Error('Frida is required for configuring a proxy.');
+
+        const session = await frida.getUsbDevice().then((f) => f.attach('SpringBoard'));
+        const script = await session.createScript(fridaScripts.setProxy(proxy));
+        await script.load();
+        await session.detach();
```
[the remark this answers is not in the document]
Comment (zner0L) [reply src/ios.ts:363]: On android we already check if a proxy/VPN is set, don't we? I guess we could also add a function in cyanoacrylate that connects to `mitm.it` to check if the traffic is going to the proxy?

[the remark this answers is not in the document]
Comment (baltpeter) [reply src/ios.ts:363]: We only did that for the VPN. I added a check for the proxy yesterday in [`c45fa4a` (#27)](https://github.com/tweaselORG/appstraction/pull/27/commits/c45fa4a0ee13c76213dd38df11d4f45b03868919).

File: src/ios.ts (hunk 2 above)
Comment (baltpeter) [reply src/ios.ts:164]: What does POSIX have to do with me not wanting to rely on shell stuff for things I can do in JS? :o

**Comment by zner0L** [comment]
Like I mentioned (https://github.com/tweaselORG/meta/issues/22#issuecomment-1478093770) Frida crashes the `SpringBoard` on iOS 15.7.2, so I can not really test this properly (my other test devices have not arrived, yet).

**Comment by zner0L** [comment]
Since we found the problem in https://github.com/tweaselORG/meta/issues/22, I was able to test this. mostly anyway, it seems that the Apps I download all seem to crash if I install them on the device. But that has nothing to do with the changes. Could you change the README and fix #55 while you're at it? Then we can merge!

**Comment by zner0L** [comment]
Just to document: I had a problem where apps wouldn't start because I had more than one mitmproxy CA on the device activated. I don't know how this could have happend, but I just deleted my `.mitmproxy/` folder, so there would have been a different certificate.

**Review by zner0L — APPROVED** [review]
I tested it now successfully and it works. Great, thank you!
